name: Cats With Gold Chains
favicon: null
layout_spectrum: 0.5123199189547449
typography_spectrum: 0.5464606606401503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3826547923963517
  lightness: 0.21811576024629176
  saturation: 0.6148385009728372
  rhythmicContrast: 0.9891281137242913
purpose: []
